-- ##bc平台的 oracle 删表脚本##

-- 设置将信息输出到控制台（如果是在SQL Plus命令行运行这个sql文件，须先行执行这个命令才能看到输出信息）
-- set serveroutput on;

-- 用于生成hibernate id的序列
CALL DROP_USER_SEQUENCE('CORE_SEQUENCE');
CALL DROP_USER_SEQUENCE('hibernate_sequence');

-- 测试用的表
CALL DROP_USER_TABLE('BC_EXAMPLE');

-- 同步记录基表
CALL DROP_USER_TABLE('BC_SYNC_BASE');

-- 用户反馈
CALL DROP_USER_TABLE('BC_FEEDBACK');

-- 电子公告
CALL DROP_USER_TABLE('BC_BULLETIN');

-- 文档附件
CALL DROP_USER_TABLE('BC_DOCS_ATTACH_HISTORY');
CALL DROP_USER_TABLE('BC_DOCS_ATTACH');

-- 系统日志
CALL DROP_USER_TABLE('BC_LOG_SYSTEM');
-- 工作日志
CALL DROP_USER_TABLE('BC_LOG_WORK');

-- 工作事务
CALL DROP_USER_TABLE('BC_WORK_TODO');
CALL DROP_USER_TABLE('BC_WORK_DONE');
CALL DROP_USER_TABLE('BC_WORK');

-- 消息管理
CALL DROP_USER_TABLE('BC_MESSAGE');

-- 个性化设置
CALL DROP_USER_TABLE('BC_DESKTOP_SHORTCUT');
CALL DROP_USER_TABLE('BC_DESKTOP_PERSONAL');

-- 系统标识
CALL DROP_USER_TABLE('BC_IDENTITY_ROLE_ACTOR');
CALL DROP_USER_TABLE('BC_IDENTITY_AUTH');
CALL DROP_USER_TABLE('BC_IDENTITY_ACTOR_RELATION');
CALL DROP_USER_TABLE('BC_IDENTITY_ACTOR_HISTORY');
CALL DROP_USER_TABLE('BC_IDENTITY_ACTOR');
CALL DROP_USER_TABLE('BC_IDENTITY_ACTOR_DETAIL');
CALL DROP_USER_TABLE('BC_IDENTITY_DUTY');
CALL DROP_USER_TABLE('BC_IDENTITY_IDGENERATOR');
CALL DROP_USER_TABLE('BC_IDENTITY_ROLE_RESOURCE');
CALL DROP_USER_TABLE('BC_IDENTITY_ROLE');
CALL DROP_USER_TABLE('BC_IDENTITY_RESOURCE');

-- 选项模块
CALL DROP_USER_TABLE('BC_OPTION_ITEM');
CALL DROP_USER_TABLE('BC_OPTION_GROUP');

-- 任务调度
CALL DROP_USER_TABLE('BC_SD_LOG');
CALL DROP_USER_TABLE('BC_SD_JOB');

-- 函数
CALL DROP_USER_FUNCTION('MD5');

-- 存储过程
CALL DROP_USER_PROCEDURE('update_actor_pcodepname');
CALL DROP_USER_PROCEDURE('update_resource_pname');
CALL DROP_USER_PROCEDURE('test_create_syslog');

-- 删除自建的存储过程
-- drop procedure DROP_USER_TABLE;
-- drop procedure DROP_USER_SEQUENCE;
-- drop procedure DROP_USER_PROCEDURE;
-- drop procedure DROP_USER_FUNCTION;

-- activiti5.6 cycle
CALL DROP_USER_TABLE('ACT_CY_CONN_CONFIG');
CALL DROP_USER_TABLE('ACT_CY_CONFIG');
CALL DROP_USER_TABLE('ACT_CY_LINK');
CALL DROP_USER_TABLE('ACT_CY_PEOPLE_LINK');
CALL DROP_USER_TABLE('ACT_CY_TAG');
CALL DROP_USER_TABLE('ACT_CY_COMMENT');
CALL DROP_USER_TABLE('ACT_CY_V_FOLDER');
CALL DROP_USER_TABLE('ACT_CY_PROCESS_SOLUTION');

-- activiti5.6 identity
CALL DROP_USER_TABLE('ACT_ID_INFO');
CALL DROP_USER_TABLE('ACT_ID_MEMBERSHIP');
CALL DROP_USER_TABLE('ACT_ID_GROUP');
CALL DROP_USER_TABLE('ACT_ID_USER');

-- activiti5.6 history
CALL DROP_USER_TABLE('ACT_HI_PROCINST');
CALL DROP_USER_TABLE('ACT_HI_ACTINST');
CALL DROP_USER_TABLE('ACT_HI_TASKINST');
CALL DROP_USER_TABLE('ACT_HI_DETAIL');
CALL DROP_USER_TABLE('ACT_HI_COMMENT');
CALL DROP_USER_TABLE('ACT_HI_ATTACHMENT');

-- activiti5.6 engine
CALL DROP_USER_TABLE('ACT_GE_PROPERTY');
CALL DROP_USER_TABLE('ACT_RU_VARIABLE');
CALL DROP_USER_TABLE('ACT_RU_JOB');
CALL DROP_USER_TABLE('ACT_GE_BYTEARRAY');
CALL DROP_USER_TABLE('ACT_RE_DEPLOYMENT');
CALL DROP_USER_TABLE('ACT_RU_IDENTITYLINK');
CALL DROP_USER_TABLE('ACT_RU_TASK');
CALL DROP_USER_TABLE('ACT_RE_PROCDEF');
CALL DROP_USER_TABLE('ACT_RU_EXECUTION');

